### ISSUE TITLE
Error after running bapp

### ISSUE THREAD

**Issue by mrmartineau** [rampouchee/bestapps#2]
Just downloaded and ran `bapp` and got this error: 

```sh
$ bapp
module.js:341
    throw err;
    ^

Error: Cannot find module './loader'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/bestapps/index.js:3:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

I did an `ls` on the module directory:

```sh
/usr/local/lib/node_modules/bestapps
 ❯ $ ls
index.js  license  node_modules  package.json  readme.md
```

You are only specifying `index.js` in the `files` part of your `package.json` which is excluding `loader.js`. I suggest removing the `files` property altogether to fix the issue.

**Comment by rampouchee** [comment]
Thanks for telling me! @estkin added fix to this
